### ISSUE TITLE
Youtube Analytics Template 

### ISSUE THREAD

**Issue by Alex-71** [migueesc123/YoutubeAnalytics#9]
Hello Miguel... 
I just runing your project successfully following your detailed instructions.   It is a nice project.
Now i'm trying to use your Analytics Template but unfortunately i'm unable to open it.   Pop up messages said that report file file is corrupt or invalid. I'm running march'18 PowerBI version.

I really thanks in advance for your help.

Regards,

Alex-

Crash Log attached...

Feedback Type:
Frown (Error)

Timestamp:
2018-03-24T22:47:34.1570945Z

Local Time:
2018-03-24T19:47:34.1570945-03:00

Session ID:
6892ac1f-b40f-427a-b403-d3350c21fa95

Release:
March 2018

Product Version:
2.56.5023.1021 (PBIDesktop) (x64)

Error Message:
'C:\Users\Alex\Youtube Analytics Template.pbit' is corrupt or an invalid report file.

Stack Trace:
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.FindPosition(Stream archiveStream)
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
   at MS.Internal.IO.Zip.ZipArchive..ctor(Stream archiveStream, FileMode mode, FileAccess access, Boolean streaming, Boolean ownStream)
   at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at Microsoft.PowerBI.Packaging.PowerBIPackager.Open(Stream storageStream, Boolean& requiresConversionToReportLayout, Byte[]& securityBindings, Boolean skipValidation)
   at Microsoft.PowerBI.Client.Windows.Services.PowerBIPackagingService.Open(FileStream fileStream, IPowerBIWindowService windowService, Nullable`1 entryPoint, Boolean& allCredentialsSatisfied)
   at Microsoft.PowerBI.Client.Windows.Services.TemplateManager.TryImportTemplate(IPowerBIWindowService windowService, IQueryServices queryServices, IExceptionHandler exceptionHandler, TelemetryUserActionId entryPoint, Boolean& editQueries, String filePath)

Stack Trace Message:
File contains corrupted data.

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.ClientShared.FeedbackErrorInfo..ctor(String message, Exception exception)
   at Microsoft.PowerBI.Client.Windows.Services.TemplateManager.TryImportTemplate(IPowerBIWindowService windowService, IQueryServices queryServices, IExceptionHandler exceptionHandler, TelemetryUserActionId entryPoint, Boolean& editQueries, String filePath)
   at Microsoft.PowerBI.Client.Windows.Commands.ApplicationCommands.DataImportCommands.ImportTemplate(IPowerBIWindowService windowService, IExceptionHandler exceptionHandler, ImportTemplateParameters parameters)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Windows.Commands.CommandFactory.<>c__DisplayClass42`1.<FromSyncHandlers>b__3f(UICommandParameter`1 p)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<>c__DisplayClass2.<.ctor>b__0(Object arg)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<Execute>d__7.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.Execute(Object parameter)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<System.Windows.Input.ICommand.Execute>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.System.Windows.Input.ICommand.Execute(Object parameter)
   at Microsoft.Practices.Prism.Commands.CompositeCommand.Execute(Object parameter)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClassa.<>c__DisplayClass10.<<Main>b__3>d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClassa.<>c__DisplayClass10.<Main>b__3(MainWindow mainWindow)
   at Microsoft.PowerBI.Client.Windows.MainWindow.<<OnMainWindowInitializationCompleted>b__4c>d__4e.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.MainWindow.<OnMainWindowInitializationCompleted>b__4c()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<HandleAwaitableAsyncExceptions>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.HandleAwaitableAsyncExceptions(IExceptionHandler exceptionHandler, Func`1 asyncFunc)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<HandleAsyncExceptions>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.HandleAsyncExceptions(IExceptionHandler exceptionHandler, Func`1 asyncFunc)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.ClientShared.WindowManager.ShowDialog[T](T form, IWindowContainer owner)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClassa.<Main>b__0()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass7.<HandleExceptionsWithNestedTasks>b__6()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)

OS Version:
Microsoft Windows NT 10.0.14393.0 (x64 en-US)

CLR Version:
4.6.2 or later [Release Number = 394802]

Peak Virtual Memory:
33.9 GB

Private Memory:
242 MB

Peak Working Set:
345 MB

IE Version:
11.2125.14393.0

User ID:
b93653de-6d24-47c0-aa5e-f037dbb20a2e

Workbook Package Info:
1* - en-US, Query Groups: 0, fastCombine: Disabled, runBackgroundAnalysis: True.

Telemetry Enabled:
True

Model Default Mode:
Import

Snapshot Trace Logs:

Enabled Preview Features:
PBI_EnableReportTheme
CustomConnectors

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_numericSlicerEnabled
PBI_SpanishLinguisticsEnabled
PBI_AdobeAnalytics
PBI_qnaExplore
PBI_variationUIChange
PBI_customVisualsGallery
PBI_canvasTooltips

Disabled DirectQuery Options:
PBI_DirectQuery_Unrestricted
TreatHanaAsRelationalSource

Cloud:
GlobalCloud

DPI Scale:
100%

Supported Services:
Power BI

Formulas:

section Section1;

**Comment by migueesc123** [comment]
Hey!

I tested the file and it worked for me, but I'm not completely sure of how to read these trace/log files from Microsoft so I just created a new pbit. Let me know if it works for you.

**Comment by Alex-71** [comment]
Hello Miguel,

Thanks for your answer.

I tried to load the new version but Power BI still has issues to load it.  Please attached image.

I’m wondering if Power BI complement is missing?


Thanks a lot for your help.


Alex

**Comment by migueesc123** [comment]
hey, would you mind posting the image again? I don't see it. Do other pbit files work you? does the connector work by itself for you?

**Comment by Alex-71** [comment]
Sure 
Here you are:

**Comment by migueesc123** [comment]
Hey Alex,

I just noticed that you're replying from your email. I'm not certain if github catches images from email replies, but I can confirm that I do not see any images yet. You might need to go through the browser experience in order to post an image. You could post a link to an image as well

**Comment by Alex-71** [comment]
Sorry Miguel... indeed i was answering from my email.
Here is the screen capture.
![img_4004](https://user-images.githubusercontent.com/37755657/37913411-34a2e204-30eb-11e8-80a1-70fa9b94917e.JPG)

**Comment by migueesc123** [comment]
do you get that same error with other template files? I'd probably send a frown to the Microsoft team to let them know what there's an issue. Are you using the Store or the msi version of Power BI Desktop? if you only have 1 version, I'd recommend that you download the other version so you can try things out on that version.

I've heard that the last February Power BI Desktop file had some issues with Power BI Templates, so that might be what's going on here. I wish that I could tell you more about making this work, but we might need to wait for the official desktop update from the Power BI Team

**Comment by Alex-71** [comment]
Hello Miguel.  I just realize that the issue is associated with the restriction Policies in my computer.   Apparently i should use other installation type.  In the meanwhile i tried installing PowerBI  a VM and Templates loaded, i could authenticate in my account, and... i have an issue loading tables. As shown in the attached image.  Probably related with null values.   But ... i'm close.

Thank you very much for your help.  
<img width="511" alt="screen shot 2018-03-26 at 18 50 37" src="https://user-images.githubusercontent.com/37755657/37935200-09bdd846-3127-11e8-9c18-220178b480b8.png">

**Comment by migueesc123** [comment]
could you scroll up in that window to see where exactly the error occurred? it should tell you exactly in what table the error first occurred

**Comment by Alex-71** [comment]
hello Miguel,

I'm pretty sure the issue is there...

![pasted_image_3_27_18__08_29](https://user-images.githubusercontent.com/37755657/37964915-882fb59c-3199-11e8-88e7-fbcb8ee2c014.jpg)
I have configured the main channel as default channel.  But apparently is no detecting content in the Field 'Dailyvideostat'.

**Comment by migueesc123** [comment]
Alex,

Sorry. I completely forgot about this thread and I thought that I  actually replied to it.

Is the problem still happening to you? I've tried multiple tests during the past few weeks and I haven't encountered this issue  before. It could be that the channel that you're trying to query doesn't have videos or views associated to it.

Looking forward to hearing from you.

**Comment by migueesc123** [comment]
Closing the ticket as did not receive any response from the requester
